apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: my_user
            - name: POSTGRES_PASSWORD
              value: "password123"
            - name: POSTGRESQL_DATABASE
              value: "my_database"
          image: docker.arvancloud.ir/postgres:15.1
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1G
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: postgres-vol
          hostPath:
            path: /var/postgres-vol
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-svc
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
